# Generated by Django 3.1.6 on 2021-02-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import issuers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=issuers.models.file_upload_path)),
                ('thumbnail', models.ImageField(upload_to=issuers.models.thumbnail_path)),
                ('created_at', models.DateField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_assets', to='issuers.issuer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
