# Generated by Django 3.1.6 on 2021-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hash',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_signed_by_issuer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_signed_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
