# Generated by Django 3.1.6 on 2021-02-21 14:17

import banks.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=banks.models.logo_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.TextField(max_length=100)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_set', to='banks.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payback_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_deadline', models.DateField(default=datetime.date.today)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_set', to='issuers.document')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_set', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_set', to='banks.bankbranch')),
            ],
        ),
    ]
