# Generated by Django 3.1.6 on 2021-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
