# Generated by Django 3.1.6 on 2021-02-18 20:38

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to=documents.models.file_upload_path)),
            ],
        ),
    ]
