# Generated by Django 3.1.6 on 2021-02-19 19:06

from django.db import migrations, models
import django.utils.timezone
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=documents.models.thumbnail_path),
            preserve_default=False,
        ),
    ]
